/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART1.h"
#include "UART1_SPI_UART.h"
#include "UART1_PINS.h"
#include "UART1_SPI_UART_PVT.h"
#include "UART1_PVT.h"
#include "UART1_BOOT.h"
#include "timer_clock.h"
#include "Timer1.h"
#include "timer_clock_1.h"
#include "IR.h"
#include "IR_aliases.h"
#include "LED.h"
#include "LED_aliases.h"
#include "ISR1.h"
#include "timer_clk2.h"
#include "M_FL.h"
#include "M_FL_aliases.h"
#include "M_BL.h"
#include "M_BL_aliases.h"
#include "M_FR.h"
#include "M_FR_aliases.h"
#include "M_BR.h"
#include "M_BR_aliases.h"
#include "Timer2.h"
#include "UART1_tx.h"
#include "UART1_tx_aliases.h"
#include "UART1_rx.h"
#include "UART1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

