# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\mac_000\Documents\Git_IR_REMO\PSoC\C4245AZI-483.cydsn\C4245AZI-483.cyprj
# Date: Fri, 11 Sep 2020 21:01:16 GMT
#set_units -time ns
create_clock -name {timer_clock_1(FFB)} -period 875 -waveform {0 437.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {timer_clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 21 43} [list]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 95 189} -nominal_period 3921.875 [list [get_pins {ClockBlock/udb_div_1}]]
create_generated_clock -name {timer_clock_2} -source [get_pins {ClockBlock/hfclk}] -edges {1 24001 48001} [list [get_pins {ClockBlock/udb_div_3}]]


# Component constraints for C:\Users\mac_000\Documents\Git_IR_REMO\PSoC\C4245AZI-483.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\mac_000\Documents\Git_IR_REMO\PSoC\C4245AZI-483.cydsn\C4245AZI-483.cyprj
# Date: Fri, 11 Sep 2020 21:01:10 GMT
